### ISSUE TITLE
[Request] Create a form displaying Covid19 information

### ISSUE THREAD

**Issue by MintoD** [ErikPDev/PluginsIdea#1]
Plugin Name: Covid19UI
Plugin Description: Show Covid-19 information
What does it do?
A form displaying Covid19 information
Bonus: https://api.covid19api.com/summary

**Comment by ErikPDev** [comment]
Working on it!

**Comment by ErikPDev** [comment]
Here it is!
[CovidUI](https://github.com/ErikPDev/CovidUI)
Do you want this to be on poggit?
