### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by llPushkarSinghll** [ErikPDev/PluginsIdea#4]
Plugin Name: Op crate and kits
Plugin Description: Op crate and kits
What does it do?
It will be too helpfull in servers

**Comment by ErikPDev** [comment]
I believe this plugin was already created.

**Comment by ErikPDev** [comment]
Comment if you you need something

**Comment by llPushkarSinghll** [comment]
Try to add hp defence and mana bar like hypixel skyblock

![images~2](https://user-images.githubusercontent.com/84075300/120369334-bce67b00-c330-11eb-8d64-01a3379c965b.jpeg)

**Comment by ErikPDev** [comment]
Alright!

**Comment by ErikPDev** [comment]
Do you want me to implement defense and mana?

**Comment by llPushkarSinghll** [comment]
Hmm implement all hp, defence and mana
